# Generated by Django 3.1.7 on 2021-04-09 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_cart_is_bought'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='bill_id',
            field=models.BigIntegerField(default=101),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checkout',
            name='price',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
