# Generated by Django 3.1.7 on 2021-04-09 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20210405_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
